# functions for genterating IEC plots

# Authors: Nicholas G. Walton and Robert W. Howe
# created: 13 Oct 2014
# Last modified: 13 Oct 2014



## LOF plot ----

plot_lof <- function(brc, min_lof = 1) {
  # brc is a data frame containging Bioric Responce Curves generated by
  # function mk_brc.
  # min_lof is minum value to label LOF values.  Values >= min_lof will be
  # labeled with their taxa in the output figure.
  #
  # Plot the lack of fit for all species on a single figure.
  # This plot is useful for spotting species with exceptionally poor LOF
  # relative to other the species.
  plot(brc$LOF, main = "Lack of Fit for all species",
       xlab = "Index (record number)", ylab = "LOF")

  for (i in 1:nrow(brc)) {
    # Label all species with a LOF greater than 1
    if (brc$LOF[i] >= min_lof) {
      text(i, brc$LOF[i], brc$Taxon[i], cex = 0.8, pos = 4)
    }
  }
}


## plot BRC with observations ----

plot_brc <- function(sp, brc, gradient) {
  # Generate scatter plot and predicted normal curve for each species.
  # One page per species.
  for (species in 1:ncol(sp)) {
    with(brc[species, ], {
      # "with" makes the following variables from data frame "brc" availabel:
      # Mean, SD, H, LOF, R2, Sens, n

      # Choose location of figure text (top right or top left side
      # of figure).
      placement <- ifelse(dnorm(0, Mean, SD) * H > 0.5 * max(sp[, species]),
                          'topright', 'topleft')

      # Generate scatter plot and predicted normal curve for current
      # species.
      # x axes label for plot.
      x_lab <- expression(Environmental ~ Condition ~ (italic(C[env])))
      plot(sp[, species] ~ gradient, main = names(sp)[species],
           xlab = x_lab, ylab = "Response", xlim = c(0, 10))
      curve(dnorm(x, Mean, SD) * H, add = TRUE)

      # Add text to plot.
      legend(placement,
             legend = c(paste("LOF:", signif(LOF, 4)),
                        as.expression(bquote(R^2: ~ .(signif(R2, 4)))),
                        as.expression(bquote(mu: ~ .(signif(Mean, 4)))),
                        as.expression(bquote(sigma: ~ .(signif(SD, 4)))),
                        paste("H:", signif(H, 4)),
                        paste("Sens:", signif(Sens, 4))),
             bty = "n")
    })
  }
}

## print BRC to pdf----

brc_pdf <- function(out_pdf, sp, brc, gradient, min_lof = 1) {
  # Unless the output figure file already exists, plot the figures.
  if (file.exists(out_pdf)) {
    # "out_pdf" is set in the "Declarations" section of this script.
    # If the output "out_pdf" already exists, print the following
    # error message:
    message(paste("Output figure file \"", out_pdf,
                  "\" already exists...\nNo figure file written.", sep = ""))
  } else {
    # Open a pdf file to write the figures to - this will be written to the
    # current working directory.
    pdf(file = out_pdf)

    tryCatch({
      plot_lof(brc, min_lof)
      plot_brc(sp, brc, gradient)

      # Print message confirming that figures were written.
      message(paste("Figures written to file \"", out_pdf, "\"", sep = ""))

    }, finally = {
      # Close the pdf.
      dev.off()
    })
  }
}


## plot responce probability curve for sites ----

plot_resp <- function (sp, iec, brc, method) {
  # this needs to be rewritten with externalized method selection and f

  # Set method/criteria for estimating IEC
  # Return function for calcLSq or calcLik based on "method"
  # Method must be set to "calcLSq" or "calcLik"
  if (method == "calcLSq") {
    criteria <- function(pc, observed) {
      # Least-squares method (AKA "calcLSq").
      # Note that currently the output from this will have the
      # Oposite sign of that from the Excel spread sheet.
      # This needs to be fixed, but will also require modifications to
      # "calcLik".
      numerator <- (observed - pc) ^ 2
      sum(numerator / pc)   # (Obs-Exp)^2 / Exp
    }
  } else {
    criteria <- function(pc, observed) {
      # Likelihood method (AKA "calcLik").
      # Calculate lack-of-fit expression ("lof") for each species.
      lof <- rep(NA, length(pc))  # set lof to length of pc.
      # If species is present at the current site, set to Log P(C).
      lof[observed > 0] <- log10(pc)[observed > 0]
      # If species is absent, set to Log (1-P(C)).
      # Per the Excel file, it's really Log(1.0001-P(C)) to avoid log of 0.
      lof[is.na(lof)] <- log10(1.0001 - pc)[is.na(lof)]

      # Return the negative sum of the lof.
      # I'm using the negative because the orignial function in Excel was
      # set to maximize, but "nlminb" can only minimize a function.
      # The result is the same.
      -sum(lof)
    }
  }

  f <- function(x) {
    # This function returns the function which
    # will be minimized with function "nlminb".
    # "x" is the current IEC score being tried by "nlminb".
    # Note that observed is called from outside the function, but there
    # doesn't seem to be a better way to do this with "nlminb".

    # Calculate P(C) for each species.
    # In the original version, P(C) was constrained to > 0 and < or = 1.
    # P(C) is the probability or value of each species at given IEC.
    # Input values "Mean", "SD", and "H" are part of data frame "brc".
    pc <- with(brc, {dnorm(x, mean = Mean, sd = SD) * H})
    pc[pc == 0] <- .001        # Set 0 probabilities to .001.

    # criteria is set in the Declarations section of this script.
    # It is set to either calcLik (default) or calcLSq.
    criteria(pc, observed)
  }

  for (site in 1:nrow(sp)) {
    # Extract the observed probabilities for the current site.
    observed <- sp[site, ]

    pts <- seq(0, 10, by = 0.2)
    resp <- -unlist(lapply(pts, function(x) f(x)))

    # this needs modfication to allow labeling for both methods.
    plot(resp ~ pts, type = "l", main = paste("Site:", row.names(sp)[site]),
         xlab = "IEC", ylab = "Sum LogLik (larger values are better)",
         xlim = c(0,10), lty = 1)

    # Add vertical line at most likely value of IEC.
    abline(v = iec$IEC[site], lty = 2)

    # Add legend to plot.
    placement <- ifelse(iec$IEC[site] < 5, 'topright', 'topleft')
    legend(placement, legend = c(expression(sum(resp[i], i == 1, n)),
                                 paste("Maxima(", round(iec$IEC[site], 2), ")",
                                       sep = "")),
           lty = c(1, 2), bty = "n")
  }
}


## plot IEC vs. orginal gradient ----
plot_iec_cor <- function (iec, sp, orig_grad, title) {
  plotstats <-lm(iec$IEC ~ orig_grad[, 1])
  R2 <- summary(plotstats)$r.squared
  slope <- summary(plotstats)$coefficient[2]

  # plot IEC site scores against reference gradient
  plot_title <- paste("IEC scores for ", title)
  grad_name  <- names(orig_grad)[1]

  plot(orig_grad[, 1], iec$IEC, xlab = paste("Original gradient:", grad_name), ylab = "IEC",
       main = plot_title, cex.sub = 0.8)
  mtext(Sys.time(), side = 3, cex = 0.8)
  abline(plotstats)

  # add legend
  if (slope < 0) {
    locate = 'topright'
  } else {
    locate = 'topleft'
  }

  legend(locate, lty = 0, bty = "n",
         legend = c(as.expression(bquote(R^2: ~ .(signif(R2, 2))))))
}
